require('config.options')
require('config.autocmds')
require('config.keybinds')
require('config.lazy')
require('features.floaterm')
require('features.statusline-toggle')
require('features.theme-manager')
