return {
  autopair = true,
  blankline = true,
  cmp = true,
  gitsigns = true,
  hop = true,
  lsp = true,
  lualine = true,
  files = true,
  indenscope = true,
  neoscroll = true,
  highlight = true,
  telescope = true,
  tiny = true,
  treesitter = true,
}
